# Generated by Django 5.0.6 on 2024-07-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_author_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_approved',
        ),
    ]
