# Generated by Django 5.0.6 on 2024-07-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_author_is_approved'),
        ('posts', '0004_alter_comment_created_at_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='author_posts', to='posts.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='user_comments', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='user_posts', to='posts.post'),
        ),
    ]
