# Generated by Django 5.0.6 on 2024-07-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_author_posts_remove_user_comments_and_more'),
        ('posts', '0004_alter_comment_created_at_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
        migrations.AddField(
            model_name='author',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='author_posts', to='posts.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='user_comments', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='user_posts', to='posts.post'),
        ),
    ]
