# Generated by Django 5.0.6 on 2024-07-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_author_posts_remove_user_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='닉네임', max_length=20, unique=True),
        ),
    ]
