# Generated by Django 5.0.6 on 2024-07-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_scrapped_remove_post_scraps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
