# Generated by Django 5.0.6 on 2024-07-03 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_hashtag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='user',
        ),
    ]
