# Generated by Django 5.0.6 on 2024-07-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_hashtag_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FR', '자유'), ('SO', '사회'), ('SC', '과학'), ('EC', '경제'), ('MU', '음악'), ('BO', '도서'), ('MO', '영화')], default='자유', max_length=2, verbose_name='글 분야'),
        ),
    ]
