# Generated by Django 5.0.6 on 2024-07-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_post_hashtag_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
