# Generated by Django 5.0.6 on 2024-07-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_delete_scrap'),
        ('posts', '0015_alter_post_category'),
    ]

    operations = [
    ]
