# Generated by Django 5.0.6 on 2024-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='img/bin_img.svg', null=True, upload_to='post_photo'),
        ),
    ]
