# Generated by Django 5.0.6 on 2024-07-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='img/bin_img.svg', upload_to='post_photo'),
        ),
    ]
