# Generated by Django 5.0.6 on 2024-07-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_post_likes_alter_like_comment_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post_photo/bin_img.svg', upload_to='post_photo'),
        ),
    ]
